# angular-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sneaker-angular-deployment
spec:
  selector:
    matchLabels:
      app: sneaker-angular
  replicas: 1
  template:
    metadata:
      labels:
        app: sneaker-angular
    spec:
      containers:
      - name: sneaker-angular
        image: lovetruongan/sneaker_fe:latest # Replace with your actual image name
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sneaker-angular-service
spec:
  type: NodePort
  selector:
    app: sneaker-angular
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
      nodePort: 30003
