# phpmyadmin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin8-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin8
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin8
    spec:
      containers:
      - name: phpmyadmin8
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: "mysql8-service"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin8-service
spec:
  type: nodePort
  selector:
    app: phpmyadmin8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
